### ISSUE TITLE
Change tab title

### ISSUE THREAD

**Issue by kate-holdener** [kate-holdener/ml_code_generator#112]
The currently deployed website shows '-Flaskr' as the title in the tab (see screenshot below). This should be changed to something that's more descriptive of this project. Maybe 'ML Code Generator". 

<img width="1711" alt="Screen Shot 2023-05-12 at 10 37 18 AM" src="https://github.com/kate-holdener/ml_code_generator/assets/42073871/cf34ef99-a40c-4ef6-843f-76bc273fc1c5">

This can be done by changing the title in the flask template (see flask docs for more details: https://flask.palletsprojects.com/en/1.1.x/tutorial/templates/ )

**Comment by ademakdogan** [comment]
I have fixed that. 
https://github.com/kate-holdener/ml_code_generator/pull/113

**Comment by kate-holdener** [comment]
Thanks, @ademakdogan. I merged your pull request and we should see the updated tab name on our live site very soon. I have other good first issues in the repo, if you are interested.
