### ISSUE TITLE
Allow user to optionally specify the train/test split percentage.

### ISSUE THREAD

**Issue by kate-holdener** [kate-holdener/ml_code_generator#17]

**Comment by kate-holdener** [comment]
The user should have the option to keep the defaults (currently set to 80/20) or specify their own values.

**Comment by felipealencar** [comment]
Hi @kate-holdener, I already finished the correction for issue #41. Can I work on this one too?

**Comment by RishiTambe** [comment]
Hi Dr. Holdener, I would like to work on this Issue.

**Comment by kate-holdener** [comment]
> 

Hi @RishiTambe, someone else is working on this one right now. Could you pick a different issue?

**Comment by kate-holdener** [comment]
Resolved with pull request #48
