### ISSUE TITLE
Run generated code in Google Colab

### ISSUE THREAD

**Issue by kate-holdener** [kate-holdener/ml_code_generator#38]
It would be really nice to allow the user to run the generated code on a cloud system. Rather than having the user copy and paste the code, our software could give the users an option to sign-in with with their google account and then upload the generated code to their google drive. Google Colab works off Google Drive, so we can use Google Drive API to do the upload. After uploading, we would give the users a link to open and run the code in Google Colab.

**Comment by kate-holdener** [comment]
Here is a useful article about using Google Login in a Flask application: https://realpython.com/flask-google-login/

**Comment by kate-holdener** [comment]
I think this could be a useful reference: https://www.mattbutton.com/2019/01/05/google-authentication-with-python-and-flask/
I'm pretty sure that Google Colab projects are saved on Google Drive. By saving code on Google Drive, we can run it on Google Colab (I think)

**Comment by john-coffman** [comment]
was completed with branch issue_75
