### ISSUE TITLE
Prepare Model - select input values - not all selected values get dropped

### ISSUE THREAD

**Issue by kate-holdener** [kate-holdener/ml_code_generator#41]
In the Prepare Model step, there is a bug in the code for selecting which input values need to be excluded from the model. Specifically, if I select more than 1 column (feature) to be dropped, the generated code only drops 1 column instead of all the columns that I selected.

**Comment by felipealencar** [comment]
Hello! @kate-holdener, I would like to work on this issue. :)

**Comment by kate-holdener** [comment]
Fixed with pull request #47
