### ISSUE TITLE
Convert non-numeric table values to numeric values

### ISSUE THREAD

**Issue by kate-holdener** [kate-holdener/ml_code_generator#42]
The current version of this software supports table data only: a user uploads a csv file where the columns are the features and the rows are the various samples. Some of the features might be non-numeric string values, for example "male" or "female". To train an ML model, these values need to be converted to discrete numeric states. For example: male - 0, female - 1. This should be done automatically right after the data is uploaded. The mapping from string to numeric value needs to be preserved for later use. For example, once we have trained the model and want to use it on a new data sample that contains "male", we would convert "male" to 0.

**Comment by KD335** [comment]
Fixed after merging the issue_63 branch with main for the first time
