### ISSUE TITLE
Refactor flask_app/flask_main.py

### ISSUE THREAD

**Issue by kate-holdener** [kate-holdener/ml_code_generator#54]
Refactor flask_main by splitting routes into multiple files and combining them using centralized URL Map (with app.add_url_rule), as described here https://flask.palletsprojects.com/en/1.1.x/patterns/lazyloading/#converting-to-centralized-url-map

**Comment by Fayhen** [comment]
Hi! I'm looking into this issue and will submit a PR for revision shortly.

**Comment by kate-holdener** [comment]
Thank you, @Fayhen! Looking forward to your PR.

**Comment by kate-holdener** [comment]
Resolved with pull request #56
