### ISSUE TITLE
Avoid displaying the wrong page when the user hits Next Action before Get Started 

### ISSUE THREAD

**Issue by john-coffman** [kate-holdener/ml_code_generator#70]
![image](https://user-images.githubusercontent.com/102572740/201972679-03ae6acc-6e98-43eb-ba52-7fe101794667.png)

This happens because it is returning actions.html and upload_data.html. I think this is because hitting next action button references "actions.html" through an href, and the maps token is set to "start" since you are on the home.html so it renders "actions./upload_data.html" since we are rendering in two places it uses both.

**Comment by kate-holdener** [comment]
Fixed with pull request #71
